### PR TITLE
DM-7502: Add missing imports 

### PR DESCRIPTION
**Pull request by hchiang2**

### CODE REVIEW

**Comment by laurenam** [comment]
Is there a reason you're not updating these tests to use lsst.log?

**Comment by hchiang2** [comment]
I'm deferring that to a future ticket. `meas_algorithms` might need to be converted before this one. Somehow these missing imports show up in Jenkins from the changes upstream in this ticket.

**Comment by hchiang2** [comment]
@laurenam it seems you closed this PR. I assume it wasn't intentional?   I'm reopening it.

**Comment by laurenam** [comment]
Arghh!  Sorry, I hit "Close and comment" instead of "Comment"!

**Pull request merged**
